config/routes.rb
RainbowMe::Application.routes.draw do
  resources :photos, only: [:create, :new, :index]

  get '/auth/:provider/callback', to: 'photos#auto'

  root 'photos#new'

  match '/stats(/:action(/:id(.:format)))', :controller => :stats, :via => [:get, :post]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :upload, PhotoUploader
  validates :upload, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photo_url = session[:photo_url]
    @download_url = session[:download_url]
  end

  def auto
    track! :auto_transform

    image_url = request.env['omniauth.auth'][:info][:image].sub("_normal\.png", "\.png")
    p=Photo.new
    p.remote_upload_url = image_url
    p.save!

    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_KEY"]
      config.consumer_secret     = ENV["TWITTER_SECRET"]
      config.access_token        = request.env['omniauth.auth'][:credentials][:token]
      config.access_token_secret = request.env['omniauth.auth'][:credentials][:secret]
    end

    file = open(p.upload_url)
    session[:photo_url] = p.upload_url
    session[:download_url] = p.upload.url(:query => {"response-content-disposition" => "attachment"})

    begin
      client.update_profile_image(file)
    rescue
      redirect_to photos_url, notice: "Something went wrong contacting Twitter. Download your photo below and manually set it as your profile picture."
      return
    end
    redirect_to photos_url, notice: "Done!"
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    track! :manual_download

    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html {
          session[:photo_url] = @photo.upload_url
          session[:download_url] = @photo.upload.url(:query => {"response-content-disposition" => "attachment"})
          redirect_to photos_url
        }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:upload)
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  include Vanity::Rails::Dashboard
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainbows for Sochi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-image:url(/rainbow_bg.png); background-repeat: no-repeat; background-size: 100%;">
<div id="notice"><%=flash[:notice]%></div>
<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :upload %>
  </div>
  <div class="actions">
    <%= f.submit 'Rainbow me for Sochi', class: 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="container">
  <div class="row">

    <div class="span10 offset1">

   <div class="hero-unit" style="line-height: 18px;">

     <h1>You've been Rainbowed!</h1>
     <h4>Please help us spread the rainbow by sharing on Twitter, Facebook etc.</h4>
     <% social_share_button_tag('I got a rainbow on my profile for LBGT solidarity during Sochi', url: root_url) %>
     <p>
      <div class="social-likes" data-url="http://rainbows-for-sochi.herokuapp.com/" data-title="Get a Rainbow for Sochi on your profile">
	<div class="facebook" title="Share link on Facebook">Facebook</div>
	<div class="twitter" data-via="h_carver" title="Share link on Twitter">Twitter</div>
	<div class="plusone" title="Share link on Google+">Google+</div>
      </div>
</p>
<a href="https://twitter.com/h_carver" class="twitter-follow-button" data-show-count="false">Created by @h_carver</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


      <div class="row-fluid">
      <div class="span12 text-center">
        <p>
        <%= link_to 'Download your photo', "#{@download_url}", {class: 'btn btn-primary'} %>
        </p>
        <img src="<%= @photo_url%>">
      </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="container">
  <div class="row">

    <div class="span8 offset2">

   <div class="hero-unit" style="line-height: 18px;">

     <h1>Rainbows for Sochi</h1>
     <p>Upload a picture here (ideally Twitter profile picture at 500x500) to rainbow-ify it.</p>
<div class="row-fluid">
<div class="span6">
<h4>Twitter (automatic)</h4>
     <a class="btn btn-primary btn-large" href="/auth/twitter">Rainbow my profile pic for me</a>
     <small style="font-size:65%; line-height: 18px;">Twitter will ask for a load of permissions but all we'll do is change your profile pic.</small>
</div>
<div class="span6">
<h4>Create a rainbowed profile pic</h4>
      <%= render 'form' %>
</div>
</div>

<p>
      <div class="social-likes" data-url="http://rainbows-for-sochi.herokuapp.com/" data-title="Get a Rainbow for Sochi on your profile">
	<div class="facebook" title="Share link on Facebook">Facebook</div>
	<div class="twitter" data-via="h_carver" title="Share link on Twitter">Twitter</div>
	<div class="plusone" title="Share link on Google+">Google+</div>
      </div>
</p>

      <a href="https://twitter.com/h_carver" class="twitter-follow-button" data-show-count="false">Follow @h_carver</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
   </div>


</div>
  </div>

app/views/photos/show.html.erb
<div class="container">
  <div class="row">

    <div class="span8 offset2">

   <div class="hero-unit" style="line-height: 18px;">

     <h1>Done!</h1>
     <p>Spread the rainbow below!</p>
     <%= social_share_button_tag('I got a rainbow on my profile for LBGT solidarity during Sochi') %>

<a href="https://twitter.com/h_carver" class="twitter-follow-button" data-show-count="false">Follow @h_carver</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <iframe src=<%=@url%/>
    </div>
  </div>
</div>